// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://picdgrmhyvjoitttaoaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpY2Rncm1oeXZqb2l0dHRhb2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzgxOTksImV4cCI6MjA3MDY1NDE5OX0.GntA62R0uwdPJZTy0HuRLWoW3c-kuE35ygTdtwq5hhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});